#!/bin/bash

# The project is designed to run at 8 MHz. 1 MHz is the default from the factory.
# It will probably work, but has not been tested.
# Before programming, I must set the 8 MHz fuses.
/home/schwager/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude -C/home/schwager/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/etc/avrdude.conf -v -patmega8 -cusbasp -Pusb -U lfuse:w:0xE4:m
